package example

object App {
  new scala.util.control.Exception.Catch(null, null, null)
}
